# Generated by Django 6.0.1 on 2026-02-02 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhoHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_kho', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(max_length=200)),
                ('lat', models.FloatField(help_text='Vĩ độ')),
                ('lng', models.FloatField(help_text='Kinh độ')),
            ],
        ),
        migrations.CreateModel(
            name='TaiXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tai_xe', models.CharField(max_length=100)),
                ('sdt', models.CharField(max_length=15)),
                ('bien_so', models.CharField(max_length=20)),
                ('loai_xe', models.CharField(choices=[('Xe máy', 'Xe máy'), ('Xe tải', 'Xe tải'), ('Xe bán tải', 'Xe bán tải')], max_length=50)),
                ('trang_thai', models.CharField(default='Sẵn sàng', max_length=20)),
                ('ca_lam_viec', models.CharField(choices=[('SANG', 'Ca Sáng (6h - 14h)'), ('CHIEU', 'Ca Chiều (14h - 22h)'), ('DEM', 'Ca Đêm (22h - 6h)')], default='SANG', max_length=10, verbose_name='Ca làm việc')),
                ('dang_lam_viec', models.BooleanField(default=False, verbose_name='Đang Online (Chấm công)')),
                ('tong_don_thang_nay', models.IntegerField(default=0, verbose_name='KPI Số đơn/Tháng')),
                ('doanh_thu_tich_luy', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Doanh thu tích lũy')),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don', models.CharField(max_length=20, unique=True)),
                ('ten_nguoi_nhan', models.CharField(max_length=100)),
                ('dia_chi_nguoi_nhan', models.CharField(max_length=200)),
                ('sdt_nguoi_nhan', models.CharField(max_length=15)),
                ('lat_khach', models.FloatField()),
                ('lng_khach', models.FloatField()),
                ('khoi_luong', models.FloatField(help_text='Đơn vị: kg')),
                ('trang_thai', models.CharField(default='Đang xử lý', max_length=50)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('kho_xuat_phat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.khohang')),
                ('tai_xe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taixe')),
            ],
        ),
    ]
