# Generated by Django 6.0.1 on 2026-03-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taixe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='khohang',
            name='suc_chua_toi_da',
            field=models.IntegerField(default=100, verbose_name='Sức chứa tối đa (Đơn)'),
        ),
    ]
