# Generated by Django 6.0.1 on 2026-03-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_khohang_suc_chua_toi_da'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='ma_don',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã đơn hàng'),
        ),
    ]
