# Generated by Django 6.0.1 on 2026-03-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_donhang_ma_don'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='ma_don',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
