# Generated by Django 6.0.1 on 2026-04-10 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_donhang_ma_don'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai_kho', models.CharField(choices=[('NHAP_KHO', 'Đã nhập kho'), ('XUAT_KHO', 'Đã xuất kho'), ('DANG_LUAN_CHUYEN', 'Đang luân chuyển')], max_length=50)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_kho', to='core.donhang')),
                ('kho_den', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.khohang')),
            ],
            options={
                'ordering': ['-thoi_gian'],
            },
        ),
    ]
