# Generated by Django 6.0.1 on 2026-04-10 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lichsukho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichsukho',
            name='kho_den',
        ),
        migrations.RemoveField(
            model_name='lichsukho',
            name='trang_thai_kho',
        ),
        migrations.AddField(
            model_name='lichsukho',
            name='kho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.khohang'),
        ),
        migrations.AddField(
            model_name='lichsukho',
            name='trang_thai_buoc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
