--
-- PostgreSQL database dump
--

\restrict IaYdNbHCVKHeIJDCIYbsvLdSCPgzyce17bf8AHWEFCaxfJXx9wEeTJLuICnhX2E

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-05-10 14:29:10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 16424)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16423)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16434)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16433)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16414)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16413)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16443)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16462)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16461)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16442)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16471)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16470)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 16600)
-- Name: core_donhang; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_donhang (
    id bigint NOT NULL,
    ma_don character varying(20) NOT NULL,
    ten_nguoi_nhan character varying(100) NOT NULL,
    dia_chi_nguoi_nhan character varying(200) NOT NULL,
    sdt_nguoi_nhan character varying(15) NOT NULL,
    lat_khach double precision NOT NULL,
    lng_khach double precision NOT NULL,
    khoi_luong double precision NOT NULL,
    trang_thai character varying(50) NOT NULL,
    ngay_tao timestamp with time zone NOT NULL,
    kho_xuat_phat_id bigint NOT NULL,
    tai_xe_id bigint
);


ALTER TABLE public.core_donhang OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16599)
-- Name: core_donhang_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_donhang ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_donhang_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 16573)
-- Name: core_khohang; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_khohang (
    id bigint NOT NULL,
    ten_kho character varying(100) NOT NULL,
    dia_chi character varying(200) NOT NULL,
    lat double precision NOT NULL,
    lng double precision NOT NULL,
    suc_chua_toi_da integer NOT NULL
);


ALTER TABLE public.core_khohang OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16572)
-- Name: core_khohang_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_khohang ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_khohang_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 16654)
-- Name: core_lichsukho; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_lichsukho (
    id bigint NOT NULL,
    thoi_gian timestamp with time zone NOT NULL,
    ghi_chu text,
    don_hang_id bigint NOT NULL,
    kho_id bigint,
    trang_thai_buoc character varying(100)
);


ALTER TABLE public.core_lichsukho OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16653)
-- Name: core_lichsukho_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_lichsukho ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_lichsukho_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 16584)
-- Name: core_taixe; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_taixe (
    id bigint NOT NULL,
    ten_tai_xe character varying(100) NOT NULL,
    sdt character varying(15) NOT NULL,
    bien_so character varying(20) NOT NULL,
    loai_xe character varying(50) NOT NULL,
    trang_thai character varying(20) NOT NULL,
    ca_lam_viec character varying(10) NOT NULL,
    dang_lam_viec boolean NOT NULL,
    tong_don_thang_nay integer NOT NULL,
    doanh_thu_tich_luy numeric(15,0) NOT NULL,
    user_id integer
);


ALTER TABLE public.core_taixe OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16583)
-- Name: core_taixe_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_taixe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_taixe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16532)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16531)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16402)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16401)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16390)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 16640)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 5153 (class 0 OID 16424)
-- Dependencies: 226
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 5155 (class 0 OID 16434)
-- Dependencies: 228
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5151 (class 0 OID 16414)
-- Dependencies: 224
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add kho hang	8	add_khohang
26	Can change kho hang	8	change_khohang
27	Can delete kho hang	8	delete_khohang
28	Can view kho hang	8	view_khohang
29	Can add tai xe	9	add_taixe
30	Can change tai xe	9	change_taixe
31	Can delete tai xe	9	delete_taixe
32	Can view tai xe	9	view_taixe
33	Can add don hang	7	add_donhang
34	Can change don hang	7	change_donhang
35	Can delete don hang	7	delete_donhang
36	Can view don hang	7	view_donhang
37	Can add lich su kho	10	add_lichsukho
38	Can change lich su kho	10	change_lichsukho
39	Can delete lich su kho	10	delete_lichsukho
40	Can view lich su kho	10	view_lichsukho
\.


--
-- TOC entry 5157 (class 0 OID 16443)
-- Dependencies: 230
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$1200000$CKGsSfeTPxfXUYIv2UBsBa$bC6Ef0M3yezLdxNrkd+7NMgJ7y6JoJ51a4vsLK1sDQ0=	\N	f	VinhBui				t	t	2026-03-23 13:58:47.074644+07
3	pbkdf2_sha256$1200000$vJUatXu2JR3k3QobKmMCws$GMHSmss8XzJUlyw2PxBqfHmTNTLHWHOLSTJX0AJmO6U=	\N	f	VinhNguyen				t	t	2026-03-23 13:58:57.300291+07
5	pbkdf2_sha256$1200000$fT90dCyIQMhcgzE4ZB51HV$J3hj+Rk1yf/1v/MLBJL3lp12t95ikiwUoUTEDY2f9qc=	\N	f	shipper2				f	t	2026-03-23 13:59:20.006475+07
6	pbkdf2_sha256$1200000$n61g01zQU7RZGRramhfQAH$DamYChrpAKRVgr9iqdxwy3hhWFJugsITetgQyYMYkO0=	\N	f	Shipper3				f	t	2026-03-23 13:59:30.161839+07
7	pbkdf2_sha256$1200000$ySCpaBJTxe6UwPU9fBVBGQ$eqwb9iMMUrUWl6MYVWkztsCQa2gDjD6vMFwTsPNY+9E=	\N	f	Shipper4				f	t	2026-03-23 13:59:38.553984+07
9	pbkdf2_sha256$1200000$vO3lGw5MweCz6iBqivMVUN$W1H14ihgqXVwTa6XdeZoJDxLARx4MDNZwQu+QFtEh+0=	2026-04-16 14:23:11.699258+07	f	Shopee				f	t	2026-04-10 15:09:12.356939+07
4	pbkdf2_sha256$1200000$PaCy0kEVsgwKYzQ5w9ZJZu$WYRw0ld08hdPpn/RgPJcFKRZ9a6C0SjSRIa406/KmrA=	2026-05-05 06:44:20.165356+07	f	Shipper1				f	t	2026-03-23 13:59:11.831504+07
1	pbkdf2_sha256$1200000$jP8RtTqNgVy9k2BtB4FX6N$5aUPx54W+etkYb1XSnDP6Lp/6wX7B5iBuHl6kOdLVnI=	2026-05-05 06:53:59.275553+07	t	tannguyen			duytan4605@gmail.com	t	t	2026-03-23 13:55:53.347999+07
\.


--
-- TOC entry 5159 (class 0 OID 16462)
-- Dependencies: 232
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 5161 (class 0 OID 16471)
-- Dependencies: 234
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5169 (class 0 OID 16600)
-- Dependencies: 242
-- Data for Name: core_donhang; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_donhang (id, ma_don, ten_nguoi_nhan, dia_chi_nguoi_nhan, sdt_nguoi_nhan, lat_khach, lng_khach, khoi_luong, trang_thai, ngay_tao, kho_xuat_phat_id, tai_xe_id) FROM stdin;
1	DH001	Khách hàng Anh Tuấn	Số 687 Đường số 13, TP.HCM	0988430127	10.804759048926512	106.70293984554205	6.4	ĐÃ GIAO THÀNH CÔNG	2026-03-23 13:57:33.024255+07	8	6
2	DH002	Khách hàng Chị Mai	Số 881 Đường số 10, TP.HCM	0984797736	10.713137010265012	106.71380251601423	12.1	ĐÃ GIAO THÀNH CÔNG	2026-03-23 13:57:33.028665+07	6	6
3	DH003	Khách hàng Cô Lan	Số 509 Đường số 15, TP.HCM	0984227939	10.746470840136947	106.64637965138891	18.4	TRẢ HÀNG VỀ KHO	2026-03-23 13:57:33.030541+07	10	9
4	DH004	Khách hàng Chú Hùng	Số 549 Đường số 8, TP.HCM	0984440365	10.763497420156625	106.64657982597949	1.8	ĐANG VẬN CHUYỂN	2026-03-23 13:57:33.032138+07	5	5
5	DH005	Khách hàng Em Linh	Số 975 Đường số 11, TP.HCM	0989109312	10.763901476779235	106.62617620937893	14.3	TRẢ HÀNG VỀ KHO	2026-03-23 13:57:33.033909+07	6	9
6	DH006	Khách hàng Bác Sơn	Số 572 Đường số 16, TP.HCM	0989954079	10.822762675509969	106.71997057378637	2.6	ĐÃ GIAO THÀNH CÔNG	2026-03-23 13:57:33.03547+07	7	3
8	DH008	Khách hàng Cậu Phong	Số 375 Đường số 6, TP.HCM	0981599362	10.808364939920782	106.74406357006484	8.3	ĐÃ GIAO THÀNH CÔNG	2026-03-23 13:57:33.038722+07	2	8
11	DH011	duy khang	Chung cư Ngô Gia Tự, Phường Vườn Lài, Thành phố Thủ Đức, Thành phố Hồ Chí Minh	999	10.762928	106.673021	2	ĐÃ HỦY	2026-04-08 17:09:10.727181+07	2	7
7	DH007	Khách hàng Dì Thủy	Số 419 Đường số 11, TP.HCM	0983216178	10.714444058718897	106.74293318588299	5.4	ĐANG VẬN CHUYỂN	2026-03-23 13:57:33.037153+07	10	1
10	DH010	Khách hàng Thím Hương	Số 753 Đường số 15, TP.HCM	0985158611	10.78241476127472	106.62621774766473	18	ĐÃ GIAO THÀNH CÔNG	2026-03-23 13:57:33.043103+07	1	1
16	DH012	Duy Tâm	Chung cư Ngô Quyền, Phường An Đông, Thành phố Thủ Đức, Thành phố Hồ Chí Minh, Việt Nam	888	10.758111	106.666145	1	CHỜ TÀI XẾ	2026-04-10 13:55:36.479336+07	1	2
20	DH015	Phu Vinh	Trường Đại học Tài nguyên và Môi trường Thành phố Hồ Chí Minh, Hẻm 236B Lê Văn Sỹ, Phường Tân Sơn Hòa, Thành phố Thủ Đức, Thành phố Hồ Chí Minh, 72215, Việt Nam	806067	10.796645	106.666776	1	CHỜ TÀI XẾ	2026-04-10 20:08:41.66626+07	5	2
21	DH016	Duy Tân	Trường Đại học Bách khoa, Đại học Quốc gia Thành phố Hồ Chí Minh, 268, Đường Lý Thường Kiệt, Khu phố 12, Phường Diên Hồng, Thành phố Thủ Đức, Thành phố Hồ Chí Minh, 70000, Việt Nam	00721841284	10.77335	106.659632	1	CHỜ LẤY HÀNG	2026-04-16 14:23:55.544476+07	1	\N
9	DH009	Khách hàng Mợ Hoa	Số 779 Đường số 18, TP.HCM	0987223085	10.833994865785009	106.649737896723	5.1	ĐÃ GIAO THÀNH CÔNG	2026-03-23 13:57:33.041325+07	6	1
\.


--
-- TOC entry 5165 (class 0 OID 16573)
-- Dependencies: 238
-- Data for Name: core_khohang; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_khohang (id, ten_kho, dia_chi, lat, lng, suc_chua_toi_da) FROM stdin;
1	Kho Tổng Quận 1	12 Lê Duẩn, Bến Nghé, Q1	10.7801	106.7006	545
2	Kho Hub Tân Bình	15 Cộng Hòa, Tân Bình	10.8015	106.6526	992
3	Kho Công Nghệ Cao Thủ Đức	Khu công nghệ cao, Thủ Đức	10.8494	106.7938	600
4	Kho Cảng Quận 7	Nguyễn Văn Linh, Q7	10.7325	106.7021	675
5	Kho Phân Phối Bình Tân	Khu Tên Lửa, Bình Tân	10.7516	106.6111	912
6	Kho Lắp Ráp Gò Vấp	Quang Trung, Gò Vấp	10.8351	106.6631	707
7	Kho Vệ Tinh Quận 9	Lê Văn Việt, Q9	10.8441	106.7963	508
8	Kho Ngoại Ô Quận 12	Nguyễn Ảnh Thủ, Q12	10.8719	106.6212	370
9	Kho Trung Chuyển Bình Chánh	Quốc lộ 50, Bình Chánh	10.7061	106.6582	357
10	Kho Cảng Nhà Bè	Huỳnh Tấn Phát, Nhà Bè	10.6865	106.7451	232
\.


--
-- TOC entry 5172 (class 0 OID 16654)
-- Dependencies: 245
-- Data for Name: core_lichsukho; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_lichsukho (id, thoi_gian, ghi_chu, don_hang_id, kho_id, trang_thai_buoc) FROM stdin;
1	2026-04-10 11:25:37.932125+07	Đã cập bến kho phân loại.	1	6	NHẬP KHO
2	2026-04-10 11:25:37.942189+07	Hàng đang được xử lý đóng gói.	1	2	ĐANG PHÂN LOẠI
3	2026-04-10 11:25:37.943101+07	Hàng đang được xử lý đóng gói.	2	3	ĐANG PHÂN LOẠI
4	2026-04-10 11:25:37.943799+07	Hàng đang được xử lý đóng gói.	2	7	ĐANG PHÂN LOẠI
5	2026-04-10 11:25:37.944477+07	Hàng đang được xử lý đóng gói.	3	2	ĐANG PHÂN LOẠI
6	2026-04-10 11:25:37.945257+07	Hàng đang được xử lý đóng gói.	3	6	ĐANG PHÂN LOẠI
7	2026-04-10 11:25:37.945832+07	Hàng đang được xử lý đóng gói.	4	8	ĐANG PHÂN LOẠI
8	2026-04-10 11:25:37.946262+07	Đã rời kho, đang luân chuyển tới bưu cục tiếp theo.	4	4	XUẤT KHO
9	2026-04-10 11:25:37.946842+07	Đã cập bến kho phân loại.	5	6	NHẬP KHO
10	2026-04-10 11:25:37.947576+07	Đã rời kho, đang luân chuyển tới bưu cục tiếp theo.	5	2	XUẤT KHO
11	2026-04-10 11:25:37.948182+07	Hàng đang được xử lý đóng gói.	6	2	ĐANG PHÂN LOẠI
12	2026-04-10 11:25:37.948802+07	Đã cập bến kho phân loại.	6	3	NHẬP KHO
13	2026-04-10 11:25:37.94929+07	Đã cập bến kho phân loại.	8	3	NHẬP KHO
14	2026-04-10 11:25:37.949838+07	Đã rời kho, đang luân chuyển tới bưu cục tiếp theo.	8	9	XUẤT KHO
15	2026-04-10 11:25:37.950345+07	Hàng đang được xử lý đóng gói.	9	4	ĐANG PHÂN LOẠI
16	2026-04-10 11:25:37.950803+07	Đã cập bến kho phân loại.	9	6	NHẬP KHO
17	2026-04-10 11:25:37.951256+07	Đã cập bến kho phân loại.	10	9	NHẬP KHO
18	2026-04-10 11:25:37.951725+07	Đã rời kho, đang luân chuyển tới bưu cục tiếp theo.	10	1	XUẤT KHO
19	2026-04-10 11:25:37.952217+07	Hàng đang được xử lý đóng gói.	11	6	ĐANG PHÂN LOẠI
20	2026-04-10 11:25:37.952693+07	Hàng đang được xử lý đóng gói.	11	8	ĐANG PHÂN LOẠI
21	2026-04-10 11:25:37.953126+07	Hàng đang được xử lý đóng gói.	7	6	ĐANG PHÂN LOẠI
22	2026-04-10 11:25:37.95367+07	Đã rời kho, đang luân chuyển tới bưu cục tiếp theo.	7	2	XUẤT KHO
23	2026-04-10 11:26:11.703472+07	Hàng đang được xử lý đóng gói.	1	6	ĐANG PHÂN LOẠI
24	2026-04-10 11:26:11.706319+07	Đã rời kho, đang luân chuyển tới bưu cục tiếp theo.	1	8	XUẤT KHO
25	2026-04-10 11:26:11.707243+07	Đã rời kho, đang luân chuyển tới bưu cục tiếp theo.	2	3	XUẤT KHO
26	2026-04-10 11:26:11.708081+07	Đã cập bến kho phân loại.	2	7	NHẬP KHO
27	2026-04-10 11:26:11.709016+07	Đã cập bến kho phân loại.	3	5	NHẬP KHO
28	2026-04-10 11:26:11.709537+07	Đã cập bến kho phân loại.	3	9	NHẬP KHO
29	2026-04-10 11:26:11.710025+07	Hàng đang được xử lý đóng gói.	4	8	ĐANG PHÂN LOẠI
30	2026-04-10 11:26:11.710432+07	Đã cập bến kho phân loại.	4	10	NHẬP KHO
31	2026-04-10 11:26:11.710813+07	Đã cập bến kho phân loại.	5	1	NHẬP KHO
32	2026-04-10 11:26:11.711205+07	Đã rời kho, đang luân chuyển tới bưu cục tiếp theo.	5	5	XUẤT KHO
33	2026-04-10 11:26:11.711649+07	Đã rời kho, đang luân chuyển tới bưu cục tiếp theo.	6	8	XUẤT KHO
34	2026-04-10 11:26:11.71228+07	Đã cập bến kho phân loại.	6	6	NHẬP KHO
35	2026-04-10 11:26:11.712947+07	Đã rời kho, đang luân chuyển tới bưu cục tiếp theo.	8	10	XUẤT KHO
36	2026-04-10 11:26:11.713633+07	Đã cập bến kho phân loại.	8	5	NHẬP KHO
37	2026-04-10 11:26:11.714257+07	Hàng đang được xử lý đóng gói.	9	6	ĐANG PHÂN LOẠI
38	2026-04-10 11:26:11.715055+07	Hàng đang được xử lý đóng gói.	9	4	ĐANG PHÂN LOẠI
39	2026-04-10 11:26:11.715788+07	Đã cập bến kho phân loại.	10	2	NHẬP KHO
40	2026-04-10 11:26:11.716315+07	Hàng đang được xử lý đóng gói.	10	1	ĐANG PHÂN LOẠI
41	2026-04-10 11:26:11.716765+07	Đã cập bến kho phân loại.	11	2	NHẬP KHO
42	2026-04-10 11:26:11.717313+07	Đã cập bến kho phân loại.	11	8	NHẬP KHO
43	2026-04-10 11:26:11.718355+07	Hàng đang được xử lý đóng gói.	7	1	ĐANG PHÂN LOẠI
44	2026-04-10 11:26:11.719659+07	Đã rời kho, đang luân chuyển tới bưu cục tiếp theo.	7	5	XUẤT KHO
45	2026-04-10 13:55:36.4965+07	Đơn hàng được khởi tạo từ Đối tác B2B.	16	1	NHẬP KHO
49	2026-04-10 20:08:41.675431+07	Đơn hàng được khởi tạo từ Đối tác B2B.	20	5	NHẬP KHO
50	2026-04-10 20:10:39.928607+07	Cập nhật bởi tài xế: Shipper1	10	1	SHIPPER CẬP NHẬT: ĐÃ GIAO THÀNH CÔNG
51	2026-04-16 14:23:55.564938+07	Đơn hàng được khởi tạo từ Đối tác B2B.	21	1	NHẬP KHO
52	2026-04-16 14:26:47.907883+07	Cập nhật bởi tài xế: Shipper1	9	6	SHIPPER CẬP NHẬT: ĐÃ GIAO THÀNH CÔNG
\.


--
-- TOC entry 5167 (class 0 OID 16584)
-- Dependencies: 240
-- Data for Name: core_taixe; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_taixe (id, ten_tai_xe, sdt, bien_so, loai_xe, trang_thai, ca_lam_viec, dang_lam_viec, tong_don_thang_nay, doanh_thu_tich_luy, user_id) FROM stdin;
2	Trần Vận Tải	0915353203	52A-54069	Xe máy	Sẵn sàng	DEM	f	56	14944931	\N
4	Phạm Hỏa Tốc	0925548044	53A-60820	Xe máy	Sẵn sàng	DEM	f	51	2433585	\N
7	Đặng An Toàn	0959462961	53A-31773	Xe máy	Sẵn sàng	CHIEU	f	58	9786033	\N
8	Bùi Uy Tín	0935330534	59A-52602	Xe máy	Sẵn sàng	SANG	f	79	12866652	\N
9	Đỗ Siêu Tốc	0994374947	54A-46242	Xe máy	Sẵn sàng	SANG	f	63	2277146	\N
10	Hồ Lộ Trình	0916247194	55A-62331	Xe bán tải	Sẵn sàng	SANG	f	23	8783921	\N
1	Nguyễn Tốc Độ	0992260702	57A-39368	Xe máy	Sẵn sàng	SANG	f	39	3322248	4
3	Lê Giao Nhanh	0990236852	57A-71947	Xe máy	Sẵn sàng	DEM	f	62	5079539	5
5	Hoàng Bưu Kiện	0957434281	51A-61515	Xe máy	Sẵn sàng	CHIEU	f	42	12282484	6
6	Vũ Đường Dài	0969349332	51A-65350	Xe tải	Sẵn sàng	DEM	f	11	2391737	7
\.


--
-- TOC entry 5163 (class 0 OID 16532)
-- Dependencies: 236
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 5149 (class 0 OID 16402)
-- Dependencies: 222
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	core	donhang
8	core	khohang
9	core	taixe
10	core	lichsukho
\.


--
-- TOC entry 5147 (class 0 OID 16390)
-- Dependencies: 220
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-03-23 13:54:49.456975+07
2	auth	0001_initial	2026-03-23 13:54:49.531524+07
3	admin	0001_initial	2026-03-23 13:54:49.553505+07
4	admin	0002_logentry_remove_auto_add	2026-03-23 13:54:49.558891+07
5	admin	0003_logentry_add_action_flag_choices	2026-03-23 13:54:49.563762+07
6	contenttypes	0002_remove_content_type_name	2026-03-23 13:54:49.575683+07
7	auth	0002_alter_permission_name_max_length	2026-03-23 13:54:49.581522+07
8	auth	0003_alter_user_email_max_length	2026-03-23 13:54:49.587443+07
9	auth	0004_alter_user_username_opts	2026-03-23 13:54:49.593387+07
10	auth	0005_alter_user_last_login_null	2026-03-23 13:54:49.599113+07
11	auth	0006_require_contenttypes_0002	2026-03-23 13:54:49.600217+07
12	auth	0007_alter_validators_add_error_messages	2026-03-23 13:54:49.60527+07
13	auth	0008_alter_user_username_max_length	2026-03-23 13:54:49.616447+07
14	auth	0009_alter_user_last_name_max_length	2026-03-23 13:54:49.622508+07
15	auth	0010_alter_group_name_max_length	2026-03-23 13:54:49.630021+07
16	auth	0011_update_proxy_permissions	2026-03-23 13:54:49.635181+07
17	auth	0012_alter_user_first_name_max_length	2026-03-23 13:54:49.642+07
18	core	0001_initial	2026-03-23 13:54:49.674437+07
19	core	0002_taixe_user	2026-03-23 13:54:49.686926+07
20	core	0003_khohang_suc_chua_toi_da	2026-03-23 13:54:49.697918+07
21	core	0004_alter_donhang_ma_don	2026-03-23 13:54:49.70243+07
22	core	0005_alter_donhang_ma_don	2026-03-23 13:54:49.707946+07
23	sessions	0001_initial	2026-03-23 13:54:49.721381+07
24	core	0006_lichsukho	2026-04-10 10:37:39.42367+07
25	core	0007_remove_lichsukho_kho_den_and_more	2026-04-10 10:46:26.63532+07
\.


--
-- TOC entry 5170 (class 0 OID 16640)
-- Dependencies: 243
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
7v2ylbm83aqqxusm1xsbyw2dflf4gdtl	.eJxVjEEOwiAQRe_C2hAMZWBcuvcMZIAZqRqalHbVeHdt0oVu_3vvbyrSutS4dp7jWNRFndXpd0uUn9x2UB7U7pPOU1vmMeld0Qft-jYVfl0P9--gUq_f2mYDgIMNGZzLLJ6CJZeKIPHgCTxKYkQDATAUIygkKQj6zITgjXp_AOwSOHE:1wALsz:0Kfxu2fT6zADQX5iB6U0skRONtaa3p6TbvXqAe5aZLc	2026-04-22 12:55:33.49182+07
fnmtrqdyp0toq5banwx60dx5b1wqbkyt	.eJxVjEEOwiAQRe_C2hAMZWBcuvcMZIAZqRqalHbVeHdt0oVu_3vvbyrSutS4dp7jWNRFndXpd0uUn9x2UB7U7pPOU1vmMeld0Qft-jYVfl0P9--gUq_f2mYDgIMNGZzLLJ6CJZeKIPHgCTxKYkQDATAUIygkKQj6zITgjXp_AOwSOHE:1wDH8k:_5AVBYi-s-RqwDl6A2L33bcntv0obUMUtBoLjXiea7c	2026-04-30 14:27:54.986221+07
b58hxhirhlrg3df8sdqxzc3ql21jv634	.eJxVjEEOwiAQRe_C2hCgCIxL956BDMMgVUOT0q6Md7dNutDte-__t4i4LjWunec4ZnERVpx-WUJ6cttFfmC7T5KmtsxjknsiD9vlbcr8uh7t30HFXrd1AZN1sFZpB0R0RnI8oFEWs0tu46CZyWlQwMGErPygGAoU8mS8NeLzBdoNN3w:1wK2xY:M52cr4bTARpuUf6jjcduTIbIKNP5GtA83FnEhZNnj-0	2026-05-19 06:44:20.172167+07
3dhd1q65waddbiyen2xqwwk1vvmd9i6f	.eJxVjEEOwiAQRe_C2hAMZWBcuvcMZIAZqRqalHbVeHdt0oVu_3vvbyrSutS4dp7jWNRFndXpd0uUn9x2UB7U7pPOU1vmMeld0Qft-jYVfl0P9--gUq_f2mYDgIMNGZzLLJ6CJZeKIPHgCTxKYkQDATAUIygkKQj6zITgjXp_AOwSOHE:1wK36t:fuGplXc33oXRVSfNFPC8GreSqVrnaOSZBbW-QgIuszM	2026-05-19 06:53:59.276937+07
b64900mbunub3rh91nlagu1ds2rz0ths	.eJxVjEEOwiAQRe_C2hAMZWBcuvcMZIAZqRqalHbVeHdt0oVu_3vvbyrSutS4dp7jWNRFndXpd0uUn9x2UB7U7pPOU1vmMeld0Qft-jYVfl0P9--gUq_f2mYDgIMNGZzLLJ6CJZeKIPHgCTxKYkQDATAUIygkKQj6zITgjXp_AOwSOHE:1wAs0y:O8iLtIkKmLFJMDCMq0ZLJlC5ZYjZTMxXGfGGC6woKAM	2026-04-23 23:13:56.160515+07
xdy746olpvhluvl71wwkzwdufx4900y8	.eJxVjEEOwiAQRe_C2hCgCIxL956BDMMgVUOT0q6Md7dNutDte-__t4i4LjWunec4ZnERVpx-WUJ6cttFfmC7T5KmtsxjknsiD9vlbcr8uh7t30HFXrd1AZN1sFZpB0R0RnI8oFEWs0tu46CZyWlQwMGErPygGAoU8mS8NeLzBdoNN3w:1wB3hn:lohnn_HI55lEYqq7C05u-kfwdZBvc7XXN17HpKCJ0Oo	2026-04-24 11:42:55.973569+07
\.


--
-- TOC entry 5178 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5179 (class 0 OID 0)
-- Dependencies: 227
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5180 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 40, true);


--
-- TOC entry 5181 (class 0 OID 0)
-- Dependencies: 231
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- TOC entry 5182 (class 0 OID 0)
-- Dependencies: 229
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 9, true);


--
-- TOC entry 5183 (class 0 OID 0)
-- Dependencies: 233
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 5184 (class 0 OID 0)
-- Dependencies: 241
-- Name: core_donhang_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_donhang_id_seq', 21, true);


--
-- TOC entry 5185 (class 0 OID 0)
-- Dependencies: 237
-- Name: core_khohang_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_khohang_id_seq', 10, true);


--
-- TOC entry 5186 (class 0 OID 0)
-- Dependencies: 244
-- Name: core_lichsukho_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_lichsukho_id_seq', 52, true);


--
-- TOC entry 5187 (class 0 OID 0)
-- Dependencies: 239
-- Name: core_taixe_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_taixe_id_seq', 10, true);


--
-- TOC entry 5188 (class 0 OID 0)
-- Dependencies: 235
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 5189 (class 0 OID 0)
-- Dependencies: 221
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 10, true);


--
-- TOC entry 5190 (class 0 OID 0)
-- Dependencies: 219
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 25, true);


--
-- TOC entry 4934 (class 2606 OID 16568)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4939 (class 2606 OID 16489)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4942 (class 2606 OID 16441)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4936 (class 2606 OID 16430)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4929 (class 2606 OID 16480)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4931 (class 2606 OID 16422)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4950 (class 2606 OID 16469)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4953 (class 2606 OID 16504)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4944 (class 2606 OID 16458)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4956 (class 2606 OID 16478)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4959 (class 2606 OID 16518)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4947 (class 2606 OID 16561)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 4973 (class 2606 OID 16617)
-- Name: core_donhang core_donhang_ma_don_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_donhang
    ADD CONSTRAINT core_donhang_ma_don_key UNIQUE (ma_don);


--
-- TOC entry 4975 (class 2606 OID 16615)
-- Name: core_donhang core_donhang_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_donhang
    ADD CONSTRAINT core_donhang_pkey PRIMARY KEY (id);


--
-- TOC entry 4965 (class 2606 OID 16582)
-- Name: core_khohang core_khohang_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_khohang
    ADD CONSTRAINT core_khohang_pkey PRIMARY KEY (id);


--
-- TOC entry 4984 (class 2606 OID 16664)
-- Name: core_lichsukho core_lichsukho_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_lichsukho
    ADD CONSTRAINT core_lichsukho_pkey PRIMARY KEY (id);


--
-- TOC entry 4967 (class 2606 OID 16598)
-- Name: core_taixe core_taixe_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_taixe
    ADD CONSTRAINT core_taixe_pkey PRIMARY KEY (id);


--
-- TOC entry 4969 (class 2606 OID 16632)
-- Name: core_taixe core_taixe_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_taixe
    ADD CONSTRAINT core_taixe_user_id_key UNIQUE (user_id);


--
-- TOC entry 4962 (class 2606 OID 16545)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4924 (class 2606 OID 16412)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4926 (class 2606 OID 16410)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4922 (class 2606 OID 16400)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4979 (class 2606 OID 16649)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4932 (class 1259 OID 16569)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4937 (class 1259 OID 16500)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4940 (class 1259 OID 16501)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4927 (class 1259 OID 16486)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4948 (class 1259 OID 16516)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 4951 (class 1259 OID 16515)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 4954 (class 1259 OID 16530)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4957 (class 1259 OID 16529)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 4945 (class 1259 OID 16562)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 4970 (class 1259 OID 16629)
-- Name: core_donhang_kho_xuat_phat_id_4d8cd2eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_donhang_kho_xuat_phat_id_4d8cd2eb ON public.core_donhang USING btree (kho_xuat_phat_id);


--
-- TOC entry 4971 (class 1259 OID 16628)
-- Name: core_donhang_ma_don_8e9e7cdb_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_donhang_ma_don_8e9e7cdb_like ON public.core_donhang USING btree (ma_don varchar_pattern_ops);


--
-- TOC entry 4976 (class 1259 OID 16630)
-- Name: core_donhang_tai_xe_id_b0e621b6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_donhang_tai_xe_id_b0e621b6 ON public.core_donhang USING btree (tai_xe_id);


--
-- TOC entry 4981 (class 1259 OID 16675)
-- Name: core_lichsukho_don_hang_id_0f14e5fb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_lichsukho_don_hang_id_0f14e5fb ON public.core_lichsukho USING btree (don_hang_id);


--
-- TOC entry 4982 (class 1259 OID 16682)
-- Name: core_lichsukho_kho_id_d2cb8b83; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_lichsukho_kho_id_d2cb8b83 ON public.core_lichsukho USING btree (kho_id);


--
-- TOC entry 4960 (class 1259 OID 16556)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4963 (class 1259 OID 16557)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4977 (class 1259 OID 16651)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4980 (class 1259 OID 16650)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4986 (class 2606 OID 16495)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4987 (class 2606 OID 16490)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4985 (class 2606 OID 16481)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4988 (class 2606 OID 16510)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4989 (class 2606 OID 16505)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4990 (class 2606 OID 16524)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4991 (class 2606 OID 16519)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4995 (class 2606 OID 16618)
-- Name: core_donhang core_donhang_kho_xuat_phat_id_4d8cd2eb_fk_core_khohang_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_donhang
    ADD CONSTRAINT core_donhang_kho_xuat_phat_id_4d8cd2eb_fk_core_khohang_id FOREIGN KEY (kho_xuat_phat_id) REFERENCES public.core_khohang(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4996 (class 2606 OID 16623)
-- Name: core_donhang core_donhang_tai_xe_id_b0e621b6_fk_core_taixe_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_donhang
    ADD CONSTRAINT core_donhang_tai_xe_id_b0e621b6_fk_core_taixe_id FOREIGN KEY (tai_xe_id) REFERENCES public.core_taixe(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4997 (class 2606 OID 16665)
-- Name: core_lichsukho core_lichsukho_don_hang_id_0f14e5fb_fk_core_donhang_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_lichsukho
    ADD CONSTRAINT core_lichsukho_don_hang_id_0f14e5fb_fk_core_donhang_id FOREIGN KEY (don_hang_id) REFERENCES public.core_donhang(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4998 (class 2606 OID 16677)
-- Name: core_lichsukho core_lichsukho_kho_id_d2cb8b83_fk_core_khohang_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_lichsukho
    ADD CONSTRAINT core_lichsukho_kho_id_d2cb8b83_fk_core_khohang_id FOREIGN KEY (kho_id) REFERENCES public.core_khohang(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4994 (class 2606 OID 16633)
-- Name: core_taixe core_taixe_user_id_aa3f1643_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_taixe
    ADD CONSTRAINT core_taixe_user_id_aa3f1643_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4992 (class 2606 OID 16546)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4993 (class 2606 OID 16551)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-05-10 14:29:10

--
-- PostgreSQL database dump complete
--

\unrestrict IaYdNbHCVKHeIJDCIYbsvLdSCPgzyce17bf8AHWEFCaxfJXx9wEeTJLuICnhX2E

